### ISSUE TITLE
Having to double click when changed values

### ISSUE THREAD

**Issue by AinRyzen** [Akascape/CTkScrollableDropdown#36]
When changing the values of an optionmenu that has your scrollable drown attacht the optionmenu has to be double click 
When i am home will give you a replica of the problem

**Comment by Betrayal5414** [comment]
> When changing the values of an optionmenu that has your scrollable drown attacht the optionmenu has to be double click When i am home will give you a replica of the problem

I have the same problem as you...
I haven't found a solution yet.

**Comment by Akascape** [comment]
@AinRyzen This should be the expected behavior for entry-based widget, the combobox dropdown buttons calls it immediately but for entry, you have to double click. Hover you just need to change this line: https://github.com/Akascape/CTkScrollableDropdown/blob/085d3d6918ea8afa52637eb35e004a5e227b126a/CTkScrollableDropdown/ctk_scrollable_dropdown.py#L106
To
```python
self.attach.bind('<Button-1>', lambda e: self._iconify(), add="+")
```
